baseURL = "https://bernardoayala.com/"
languageCode = "en-us"
title = "Bernardo Ayala"
theme = "hugo-vitae"
paginate = 100

copyright = "Diseño inspirado en el [blog](https://www.taniarascia.com/) de [Tania Rascia](https://twitter.com/taniarascia)"

googleAnalytics = "UA-171249207-1"
disqusShortname = "bernardoayala"

[permalinks]
  posts = "/:slug/"
  pages = "/:title/"
  categories = "/:title/"
  tags = "/:title/"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe= true

[taxonomies]
	tag = "tags"
	series = "series"
  category = "categories"

[params]
	subtitle = "Frontend developer"

	# Optional 80x80 avatar image.
	avatar = "/img/glasses.svg"

  # Profile picture
  profilePicture = "/img/profile-picture.png"

  # Greeting message
  greetingMessage = "¡Hola! Soy Bernardo"

  # Small about me
  about = "Soy un desarrollador Frontend. Este es un espacio donde escribo guías sobre cosas que he ido aprendiendo, así como también opiniones y artículos de humor."

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]

	# Custom CSS applied to default styles.
	customCSS = "css/custom.css"

  description = "Bernardo Ayala - Frontend developer"

[social]
  github = "nardoyala"

# Nav.

[[menu.main]]
name = "Sobre mi"
url = "/sobre-mi"
weight = 1

[[menu.main]]
name = "Contacto"
url = "/contacto"
weight = 2

# List of tools used to build the page
[[params.tools]]
  name = "Hugo"
  title = "Built with HUGO"
  icon = "/img/icons/hugo.png"
  url = "https://gohugo.io/"

[[params.tools]]
  name = "icons8"
  title = "Icons from icons8"
  icon = "/img/icons/icons8.png"
  url = "https://icons8.com/"

[[params.tools]]
  name = "Netlify"
  title = "Hosted by Netlify"
  icon = "/img/icons/netlify.png"
  url = "/img/icons/netlify.png"

[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/nardoyala"

[[params.social]]
name = "Twitter"
icon = "fab fa-twitter"
url = "https://twitter.com/nardoyala"

