baseURL = "https://bernardoayala.com/"
DefaultContentLanguage = "es"
languageCode = "es-es"
title = "Bernardo Ayala"
theme = "hugo-floppy"
paginate = 100

copyright = "Diseño inspirado en el blog de [Tania Rascia](https://www.taniarascia.com)"

[permalinks]
  posts = "/:slug/"
  pages = "/:title/"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe= true

[taxonomies]
	tag = "tags"
	series = "series"
  category = "categories"

[params]
	subtitle = "Frontend developer"

	# Optional 80x80 avatar image.
	avatar = "/img/icons/defragment.png"

  # Profile picture
  profilePicture = "/img/profile-picture.webp"

  # Greeting message
  greetingMessage = "¡Hola! Soy Bernardo Ayala \n Frontend Developer"

  # Small about me
  about = "En este blog escribo sobre las cosas que he ido aprendiedno respecto al mundo del desarrollo web, así como de otros temas variados. Puedes encontrar guías, explicaciones, opiniones y artículos de humor."

	# Custom CSS applied to default styles.
	customCSS = "css/custom.css"

  description = "Bernardo Ayala - Frontend developer"

# Nav.

[[menu.main]]
name = "Sobre mi"
url = "/sobre-mi"
weight = 1

[[menu.main]]
name = "Contacto"
url = "/contacto"
weight = 2

# List of tools used to build the page
[[params.tools]]
  name = "Hugo"
  title = "Built with HUGO"
  icon = "/img/icons/hugo.png"
  url = "https://gohugo.io/"

[[params.tools]]
  name = "icons8"
  title = "Icons from icons8"
  icon = "/img/icons/icons8.png"
  url = "https://icons8.com/"

[[params.tools]]
  name = "Netlify"
  title = "Hosted by Netlify"
  icon = "/img/icons/netlify.png"
  url = "https://www.netlify.com/"

[[params.social]]
name = "Github"
icon = "icon-github"
url = "https://github.com/nardoyala"

[[params.social]]
name = "LinkedIn"
icon = "icon-linkedin"
url = "https://linkedin.com/nardoyala"

[[params.social]]
name = "Twitter"
icon = "icon-twitter"
url = "https://twitter.com/nardoyala"

