baseURL = "https://bernardoayala.com/"
DefaultContentLanguage = "es"
languageCode = "es-es"
title = "Bernardo Ayala"
theme = "hugo-floppy"
paginate = 10

[permalinks]
  posts = "/:slug/"
  pages = "/:title/"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe= true

[taxonomies]
	tag = "tags"
	series = "series"
  category = "categories"

# Nav.

[[menu.main]]
name = "Sobre mi"
url = "/sobre-mi"
weight = 1


[[menu.main]]
name = "Blog"
url = "/posts"
weight = 2

[params]

  # Site description
  description = "Bernardo Ayala: Desarrollador Frontend. Este es mi sitio personal donde comparto un poco de mi vida, mis conocimientos y cualquier tema que me interese o divertido."

  # Site featured image
  images = ["/img/profile-picture.webp"]

	# Optional 80x80 avatar image.
	avatar = "/img/icons/defragment.png"

  # Profile picture
  profilePicture = "/img/profile-picture.webp"

  # Greeting message
  greetingMessage = "¡Hola! Soy Bernardo"

  # Small about me
  about = "Soy desarrollador Frontend. Este es mi sitio personal donde comparto un poco de mi vida, mis conocimientos y cualquier tema que me interese o divertido."

  # Numbers of articles for index
  recentArticles = 5

	# Custom CSS applied to default styles.
	customCSS = "css/custom.css"

  # List of tools used to build the page
  [[params.tools]]
    name = "Hugo"
    title = "Built with HUGO"
    icon = "/img/icons/hugo.png"
    url = "https://gohugo.io/"

  [[params.tools]]
    name = "icons8"
    title = "Icons from icons8"
    icon = "/img/icons/icons8.png"
    url = "https://icons8.com/"

  [[params.tools]]
    name = "Netlify"
    title = "Hosted by Netlify"
    icon = "/img/icons/netlify.png"
    url = "https://www.netlify.com/"

  [[params.social]]
  name = "GitHub"
  icon = "icon-github"
  url = "https://github.com/nardoayala"

  [[params.social]]
  name = "LinkedIn"
  icon = "icon-linkedin"
  url = "https://linkedin.com/in/bernardoayala"

  [[params.social]]
  name = "Twitter"
  icon = "icon-twitter"
  url = "https://twitter.com/nardoayala"

