baseURL = "https://bernardoayala.com/"
DefaultContentLanguage = "es"
languageCode = "es-es"
title = "Bernardo Ayala"
theme = "hugo-floppy"
paginate = 10

[permalinks]
  posts = "/:slug/"
  pages = "/:title/"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe= true

[taxonomies]
	tag = "tags"
	series = "series"
  category = "categories"

[params]

  # Site description
  description = "Frontend developer and open source contributor. This is my personal blog."
  
  # Site featured image
  images = ["/img/profile-picture.webp"]

	# Optional 80x80 avatar image.
	avatar = "/img/icons/defragment.png"

  # Profile picture
  profilePicture = "/img/profile-picture.webp"

  # Greeting message
  greetingMessage = "¡Hola! Soy Bernardo Ayala"

  # Small about me
  about = "Soy un Frontend developer viviendo en una distopía tropical. Este es el espacio donde organizo mis ideas y las comparto con el mundo. Puedes encontrar guías, explicaciones, opiniones y artículos de humor."

	# Custom CSS applied to default styles.
	customCSS = "css/custom.css"

# Nav.

[[menu.main]]
name = "Sobre mi"
url = "/sobre-mi"
weight = 1

[[menu.main]]
name = "Contacto"
url = "/contacto"
weight = 2

# List of tools used to build the page
[[params.tools]]
  name = "Hugo"
  title = "Built with HUGO"
  icon = "/img/icons/hugo.png"
  url = "https://gohugo.io/"

[[params.tools]]
  name = "icons8"
  title = "Icons from icons8"
  icon = "/img/icons/icons8.png"
  url = "https://icons8.com/"

[[params.tools]]
  name = "Netlify"
  title = "Hosted by Netlify"
  icon = "/img/icons/netlify.png"
  url = "https://www.netlify.com/"

[[params.social]]
name = "GitHub"
icon = "icon-github"
url = "https://github.com/nardoyala"

[[params.social]]
name = "LinkedIn"
icon = "icon-linkedin"
url = "https://linkedin.com/in/nardoyala"

[[params.social]]
name = "Twitter"
icon = "icon-twitter"
url = "https://twitter.com/nardoyala"

