baseURL = "https://bernardoayala.com"
languageCode = "en-us"
title = "Bernardo Ayala"
theme = "hugo-vitae"
paginate = 100

copyright = "Diseño inspirado en el [blog](https://www.taniarascia.com/) de [Tania Rascia](https://twitter.com/taniarascia)"

googleAnalytics = "UA-171249207-1"
disqusShortname = "bernardoayala"

[permalinks]
  posts = "/:slug/"
  pages = "/:title/"
  categories = "/:title/"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe= true

[taxonomies]
	tag = "tags"
	series = "series"
  category = "categories"

[params]
	subtitle = "Frontend developer"

	# Optional 80x80 avatar image.
	avatar = "/img/glasses.svg"

  # Profile picture
  profilePicture = "/img/profile-picture.png"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]

	# Custom CSS applied to default styles.
	customCSS = "css/custom.css"

  description = "Bernardo Ayala - Frontend developer"

# Nav.

[[menu.main]]
name = "Sobre mi"
url = "/sobre-mi"
weight = 1

[[menu.main]]
name = "Contacto"
url = "/contacto"
weight = 2


